### ISSUE TITLE
Wrong RestrictedTrafficArea

### ISSUE THREAD

**Issue by w4bo** [w4bo/welaser-datamodels#37]
Hi @luisemmi 

`landLocation` seems not to be a valid attribute for restricted traffic areas:
See https://swagger.lab.fiware.org/?url=https://smart-data-models.github.io/dataModel.Transportation/RestrictedTrafficArea/swagger.yaml

Probably, you should replace `landLocation` with `location`
- https://github.com/w4bo/welaser-datamodels/blob/master/RestrictedTrafficArea/examples/Restricted1.json
- https://github.com/w4bo/welaser-datamodels/blob/master/RestrictedTrafficArea/examples/Restricted2.json
- https://github.com/w4bo/welaser-datamodels/blob/master/RestrictedTrafficArea/examples/Restricted3.json

**Comment by luisemmi** [comment]
Hi Matteo,
I think we have already solved this issue
Best regards
Luis
